package int_.esa.eo.ngeo.downloadmanager.settings;

public enum NonUserModifiableSetting {
	DM_IS_REGISTERED,
	DM_IS_SETUP,
	DM_ID,
	NGEO_WEB_SERVER_REGISTRATION_URLS,
	NGEO_WEB_SERVER_DAR_MONITORING_URLS,
	NGEO_WEB_SERVER_NON_UMSSO_LOGIN_URL,
	NGEO_MONITORING_SERVICE_SET_TIME,
	IICD_D_WS_REFRESH_PERIOD,
	DIR_PLUGINS
}
