package int_.esa.eo.ngeo.downloadmanager.settings;

public enum UserModifiableSetting {
	SSO_USERNAME,
	SSO_PASSWORD,
	DM_FRIENDLY_NAME,
	BASE_DOWNLOAD_FOLDER_ABSOLUTE,
	NO_OF_PARALLEL_PRODUCT_DOWNLOAD_THREADS,
	PRODUCT_DOWNLOAD_COMPLETE_COMMAND,
	WEB_INTERFACE_PASSWORD,
	WEB_INTERFACE_PORT_NO,
	WEB_INTERFACE_REMOTE_ACCESS_ENABLED,
	WEB_INTERFACE_USERNAME,
	WEB_PROXY_HOST,
	WEB_PROXY_PORT,
	WEB_PROXY_USERNAME,
	WEB_PROXY_PASSWORD
}
